<?php
/**
 * @var $block \Packt\TweetsAbout\Block\Tweets
 */
?>

<div id="wrapper">
    <div id="columns">
        <?php foreach ($block->getTweets() as $tweet) : ?>
        <div class="tweet">
            <p>
                <a href="<?php echo $tweet->user->url ?>">
                    <img src="<?php echo $tweet->user->profile_image_url ?>" alt="profile">
                </a>
                <b>Created: </b><?php echo $tweet->created_at ?>
                <br />
                <br />

                <a href="<?php echo $block->getTweetUrl($tweet) ?>" target="_blank">
                    <?php echo $tweet->text ?>
                </a>
            </p>
        </div>
        <hr />
        <?php endforeach ?>
    </div>
</div>
